# Generated by Django 4.1.7 on 2023-04-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "order_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="cart.cart",
                    ),
                ),
                ("is_delivered", models.BooleanField(default=False)),
                ("address", models.CharField(max_length=200)),
                ("comment", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
